
function atualizarEstados() {
    const paisSelect = document.getElementById("pais");
    const estadoSelect = document.getElementById("estado");
    const cidadeSelect = document.getElementById("cidade");

    estadoSelect.innerHTML = "<option value=''>Selecione um estado</option>";
    cidadeSelect.innerHTML = "<option value=''>Selecione uma cidade</option>";

    if (paisSelect.value) {
        const estados = Object.keys(dados[paisSelect.value]);

        estados.forEach(estado => {
            const option = document.createElement("option");
            option.value = estado;
            option.textContent = estado;
            estadoSelect.appendChild(option);
        });
    }
}

function atualizarCidades() {
    const paisSelect = document.getElementById("pais");
    const estadoSelect = document.getElementById("estado");
    const cidadeSelect = document.getElementById("cidade");

    cidadeSelect.innerHTML = "<option value=''>Selecione uma cidade</option>";

    if (estadoSelect.value) {
        const cidades = dados[paisSelect.value][estadoSelect.value];

        cidades.forEach(cidade => {
            const option = document.createElement("option");
            option.value = cidade;
            option.textContent = cidade;
            cidadeSelect.appendChild(option);
        });
    }
}




const dados = {
    BR: {
        "Acre": ["Acrelândia", "Assis Brasil", "Brasiléia", "Bujari", "Capixaba","Cruzeiro do Sul", "Epitaciolândia", "Feijó", "Jordão", "Mâncio Lima","Manoel Urbano", "Marechal Thaumaturgo", "Plácido de Castro", "Porto Acre","Porto Walter", "Rio Branco", "Rodrigues Alves", "Santa Rosa do Purus","Sena Madureira", "Senador Guiomard", "Tarauacá", "Xapuri"],

        "Alagoas": ["Água Branca", "Anadia", "Arapiraca", "Atalaia", "Barra de São Miguel", "Barra de Santo Antônio","Batalha", "Belo Monte", "Boca da Mata", "Branquinha", "Cacimbinhas", "Cajueiro", "Campestre", "Campo Alegre", "Campo Grande", "Canapi", "Capela", "Carneiros", "Chã Preta", "Coité do Nóia", "Colônia Leopoldina","Delmiro Gouveia", "Dois Riachos", "Estrela de Alagoas", "Feira Grande", "Feliz Deserto", "Flexeiras","Girau do Ponciano", "Ibateguara", "Igaci", "Igreja Nova", "Inhapi", "Jacaré dos Homens", "Jacuípe","Japaratinga", "Jaramataia", "Jequiá da Praia", "Joaquim Gomes", "Jundiá", "Junqueiro", "Lagoa da Canoa", "Limoeiro de Anadia", "Maceió", "Major Isidoro", "Mar Vermelho", "Maragogi", "Maravilha", "Marechal Deodoro","Mata Grande", "Matriz de Camaragibe", "Murici", "Novo Lino", "Olho d'Água das Flores", "Olho d'Água do Casado", "Olho d'Água do Piauí", "Palestina", "Palmeira dos Índios", "Pão de Açúcar", "Pariconha", "Paripueira", "Passo do Camaragibe", "Paulo Jacinto", "Penedo", "Piaçabuçu", "Pilar", "Pindoba", "Piranhas", "Poço das Trincheiras", "Porto Real do Colégio", "Quebrangulo", "Rio Largo", "Roteiro", "Santa Luzia do Norte", "Santana do Ipanema", "Santana do Mundaú", "São Brás", "São José da Laje", "São José da Tapera", "São Luís do Quitunde", "São Miguel dos Campos", "São Miguel dos Milagres", "São Sebastião", "Satuba", "Senador Rui Palmeira", "Tanque d'Arca", "Taquarana", "Teotônio Vilela", "Traipu", "União dos Palmares", "Viçosa"],

        "Amapá":["Amapá", "Amparo do Sul", "Calçoene", "Cutias", "Ferreira Gomes", "Itaubal", "Laranjal do Jari",
            "Macapá", "Mazagão", "Oiapoque", "Pedra Branca do Amapari", "Porto Grande", "Santana", "São Joaquim do Pacuí","São Paulo de Olivença", "Tartarugalzinho", "Vitória do Jari"],
            
        "Amazonas": [ "Alvarães", "Amaturá", "Anamã", "Anori", "Apuí", "Atalaia do Norte", "Autazes", "Barreirinha",
            "Benjamin Constant", "Beruri", "Boa Vista do Ramos", "Boca do Acre", "Borba", "Caapiranga",
            "Canutama", "Carauari", "Careiro", "Coari", "Codajás", "Eirunepé", "Envira", "Fonte Boa",
            "Guajará", "Humaitá", "Ipixuna", "Iranduba", "Itacoatiara", "Itamarati", "Itapiranga",
            "Japurá", "Juruá", "Jutaí", "Lábrea", "Manacapuru", "Manaquiri", "Manaus", "Manicoré",
            "Maraã", "Maués", "Nhamundá", "Nova Olinda do Norte", "Novo Airão", "Novo Aripuanã",
            "Parintins", "Pauini", "Presidente Figueiredo", "Rio Preto da Eva", "Santa Isabel do Rio Negro",
            "Santo Antônio do Içá", "São Gabriel da Cachoeira", "São Paulo de Olivença",
            "São Sebastião do Uatumã", "Silves", "Tabatinga", "Tapauá", "Tefé", "Tonantins", "Uarini",
            "Urucará", "Urucurituba"],

        "Bahia": [ "Abaré", "Adustina", "Água Fria", "Aiquara", "Alagoinhas", "Amargosa", "Amélia Rodrigues", "Antas","Antônio Cardoso", "Aporá", "Aracatu", "Araci", "Aramari", "Arataca", "Aratuipe", "Aurelino Leal","Baianópolis", "Baixa Grande", "Banzaê", "Barra", "Barra da Estiva", "Barra do Choça", "Barra do Mendes","Barra do Rocha", "Barreiras", "Barrocas", "Barrocas", "Belmonte", "Boa Nova", "Bom Jesus da Lapa","Bom Jesus da Serra", "Boninal", "Bonito", "Boquira", "Botuporã", "Brejões", "Brejolândia", "Brotas de Macaúbas","Caatiba", "Cabaceiras do Paraguaçu", "Cachoeira", "Caculé", "Caém", "Caetité", "Cafarnaum", "Cairu","Camaçari", "Camamu", "Campo Alegre de Lourdes", "Campo Formoso", "Canarana", "Canavieiras", "Candeias","Candiba", "Cansanção", "Cantanhede", "Capela do Alto Alegre", "Caraíbas", "Caravelas", "Cardeal da Silva","Carinhanha", "Castro Alves", "Catolândia", "Catu", "Catu de Abrantes", "Catuípe", "Central", "Chorrochó","Cipó", "Coaraci", "Cocoa", "Cordeiros", "Coribe", "Correntina", "Cotegipe", "Cravolândia", "Cristópolis","Cruz das Almas", "Curaçá", "Dias d'Ávila", "Dom Basílio", "Dom Macedo Costa", "Encruzilhada", "Entre Rios","Esplanada", "Euclides da Cunha", "Eunápolis", "Fátima", "Feira de Santana", "Filadélfia", "Firmino Alves","Floresta", "Formosa do Rio Preto", "Gandu", "Gavião", "Gente", "Gentio do Ouro", "Gongogi", "Governador Lomanto","Guajeru", "Guanambi", "Guaratinga", "Heliópolis", "Ibiassucê", "Ibiquera", "Ibititá", "Ibotirama", "Ichu","Igaporã", "Igrapiúna", "Iguaí", "Ilhéus", "Imbassaí", "Inhambupe", "Ipecaetá", "Ipiaú", "Ipirá", "Ipuã","Iramaia", "Irecê", "Irioná", "Itabela", "Itabuna", "Itacaré", "Itagi", "Itagibá", "Itagimirim", "Itajuípe","Itamaraju", "Itamari", "Itambé", "Itanagra", "Itanhém", "Itaparica", "Itapé", "Itapebi", "Itapetinga","Itapicuru", "Itapitanga", "Itaquara", "Itaquatinga", "Itarantim", "Itarantim", "Itatiaia", "Itirucu","Itiruçú", "Itororó", "Ituaçu", "Ituberá", "Iuiú", "Jaborandi", "Jacobina", "Jaguaquara", "Jaguarari","Jaguaripe", "Jandaíra", "Jangada", "Jânio Quadros", "Jânio Quadros", "Jéquié", "Jeremoabo", "Jiquiriçá","Jitaúna", "João Dourado", "Joaquim Gomes", "Juazeiro", "Jussara", "Jussiape", "Lafaiete Coutinho","Lagoa da Confusão", "Lagoa Grande", "Laje", "Lajeado", "Lauro de Freitas", "Lençóis", "Macarani","Macaúbas", "Mairi", "Malhada", "Malhada de Pedras", "Manoel Vitorino", "Mansidão", "Maracás", "Maragogipe",
        "Marau", "Marcionílio Souza", "Marcolândia", "Mário de Almeida", "Medeiros Neto", "Morro do Chapéu","Mucugê", "Mucuri", "Mundo Novo", "Muniz Ferreira", "Muritiba", "Mutuípe", "Mucuri", "Mata de São João","Mata de São João", "Olindina", "Oliveira dos Brejinhos", "Ouriçangas", "Pau Brasil", "Pau da Lima","Paulo Afonso", "Pedro Alexandre", "Periperi", "Piritiba", "Planaltino", "Planalto", "Pojuca", "Ponto Novo","Porto Seguro", "Riachão das Neves", "Riachão do Jacuípe", "Ribeira do Pombal", "Ribeirão do Largo","Rio de Contas", "Rio do Antônio", "Rio do Pires", "Rodelas", "Santa Bárbara", "Santa Brígida", "Santa Cruz","Santa Cruz Cabrália", "Santa Inês", "Santa Luzia", "Santa Maria da Vitória", "Santa Rita de Cássia","Santa Teresinha", "Santaluz", "Santo Amaro", "Santo Antônio de Jesus", "Santo Estevão", "São Desidério","São Francisco do Conde", "São Gabriel", "São Gonçalo dos Campos", "São João do Paraíso", "São Sebastião do Passé","São Tomé", "Sapeaçu", "Sátiro Dias", "Serra Dourada", "Serra Grande", "Serra Preta", "Serra do Ramalho","Serrolândia", "Simões Filho", "Sítio do Mato", "Sítio do Quinto", "Sobradinho", "Souto Soares", "Tabocas do Brejo Velho","Tanhaçu", "Tanhaçu", "Tanquinho", "Taperoá", "Teixeira de Freitas", "Teofilândia", "Teolândia", "Teodoro Sampaio","Terra Nova", "Tucano", "Uauá", "Uibaí", "Umburanas", "Una", "Urandi", "Uruçuca", "Valença", "Valente","Várzea da Roça", "Várzea do Poço", "Várzea Grande", "Vera Cruz", "Vitorino Freire", "Wagner", "Xique-Xique"],

        "Ceará": ["Acarape", "Acarau", "Acaraú", "Acopiara", "Aiuaba", "Alcântaras", "Altaneira", "Alto Santo", "Amontada","Antonina do Norte", "Apuiarés", "Aquiraz", "Aracati", "Aracoiaba", "Ararendá", "Araricá", "Araripe","Aratuba", "Arneiroz", "Assaré", "Assunção", "Aquiraz", "Baixio", "Banabuiú", "Barbalha", "Barreira","Barro", "Baturité", "Beberibe", "Bela Cruz", "Boa Viagem", "Brejo Santo", "Camocim", "Campos Sales","Canindé", "Capistrano", "Caridade", "Cariré", "Caririaçu", "Carnaubal", "Cascavel", "Castanhão","Catunda", "Caucaia", "Cedro", "Chorozinho", "Choró", "Crateús", "Crato", "Croatá", "Deputado Irapuan Pinheiro","Ererê", "Eusébio", "Farias Brito", "Forquilha", "Fortaleza", "Fortim", "Frecheirinha", "General Sampaio","Graça", "Granja", "Groaíras", "Guaraciaba do Norte", "Guaramiranga", "Icapuí", "Icó", "Iguatu", "Independência","Ipaporanga", "Ipaumirim", "Ipu", "Ipuã", "Iracema", "Iracema", "Irauçuba", "Itaiçaba", "Itaitinga", "Itapajé","Itapipoca", "Itapipoca", "Itapagé", "Itapiúna", "Itarema", "Itarema", "Itatira", "Jaguaribara", "Jaguaribe","Jaguaruana", "Jardim", "Jardim de Piranhas", "Jati", "Jijoca de Jericoacoara", "Juazeiro do Norte", "Jucás","Jucás", "Jucurutu", "Limoeiro do Norte", "Madalena", "Maracanaú", "Maranguape", "Marco", "Martinópole","Massapê", "Mauriti", "Meruoca", "Milagres", "Missão Velha", "Mombaça", "Monsenhor Tabosa", "Morada Nova","Morau", "Morrinhos", "Mucambo", "Mulungu", "Nova Russas", "Novas Russas", "Novo Oriente", "Ocara", "Oliveira dos Brejinhos","Orós", "Pacajus", "Pacatuba", "Pacoti", "Pacujá", "Palhano", "Parambu", "Paramoti", "Parangaba", "Parazinho","Pedra Branca", "Penaforte", "Pentecoste", "Pereiro", "Pindoretama", "Piquet Carneiro", "Pires Ferreira", "Poranga","Porteiras", "Potengi", "Potiretama", "Quiterianópolis", "Quixadá", "Quixelo", "Quixeramobim", "Quixere","Reriutaba", "Russas", "Saboeiro", "Salitre", "Santa Quitéria", "Santana do Acaraú", "Santana do Cariri","São Benedito", "São Gonçalo do Amarante", "São João do Jaguaribe", "São João do Jaguaribe", "São Luís do Curu","São Pedro", "São Tiago", "São Vicente", "Senador Pompeu", "Senador Sá", "Sobral", "Solonópole", "Tabuleiro do Norte","Tamboril", "Tauá", "Tejuçuoca", "Tianguá", "Trairi", "Tururu", "Ubajara", "Umari", "Uruburetama", "Uruoca","Varjota", "Várzea Alegre", "Vazeiro", "Viçosa do Ceará", "Vila Velha", "Vitoria do Jari", "Várzea Alegre"],

        "Distrito Federal": [ "Brasília", "Ceilândia", "Taguatinga", "Planaltina", "Sobradinho", "Gama", "Santa Maria","Águas Claras","Cruzeiro", "Samambaia", "São Sebastião", "Recanto das Emas", "Riacho Fundo I", "Riacho Fundo II", "SIA","SCIA", "Varjão", "Jardim Botânico", "Lago Sul", "Lago Norte", "Guará", "Núcleo Bandeirante"],

        "Espírito Santo": ["Afonso Cláudio", "Águia Branca", "Alegre", "Alfredo Chaves", "Alto Rio Novo", "Anchieta","Apiacá", "Aracruz","Atílio Vivácqua", "Boa Esperança", "Bom Jesus do Norte", "Brejetuba", "Cachoeiro de Itapemirim", "Cariacica","Castelo", "Colatina", "Conceição da Barra", "Conceição do Castelo", "Divino São Lourenço", "Domingos Martins","Dores do Rio Preto", "Ecoporanga", "Fundão", "Guaçuí", "Guarapari", "Ibatiba", "Ibiporã", "Iconha","Irupi", "Itaguaçu", "Itapemirim", "Itarana", "Iúna", "Jaguaré", "Jerônimo Monteiro", "João Neiva","Laranja da Terra", "Linhares", "Mantenópolis", "Marataízes", "Marechal Floriano", "Mimoso do Sul", "Montanha","Mucurici", "Muniz Freire", "Muqui", "Nova Venécia", "Novo Horizonte", "Pancas", "Pedro Canário", "Pinheiros","Piracicaba", "Ponto Belo", "Presidente Kennedy", "Rio Bananal", "Rio Novo do Sul", "Santa Leopoldina","Santa Maria de Jetibá", "Santa Teresa", "São Domingos do Norte", "São Gabriel da Palha", "São José do Calçado","São Mateus", "São Roque do Canaã", "São Sebastião do Alto", "Serra", "Sooretama", "Vargem Alta", "Venda Nova do Imigrante","Viana", "Vila Pavão", "Vila Valério", "Vila Velha", "Vitória"],

        "Goiás": [ "Abadia de Goiás", "Abadiânia", "Acreúna", "Adelândia", "Água Fria de Goiás", "Água Limpa", "Avelinópolis","Barro Alto", "Bela Vista de Goiás", "Bom Jardim de Goiás", "Bom Jesus de Goiás", "Bonópolis", "Brazabrantes","Britânia", "Buritinópolis", "Cabeceiras", "Cachoeira Alta", "Cachoeira de Goiás", "Cairo", "Caldas Novas","Campestre de Goiás", "Campinaçu", "Campinorte", "Campo Alegre de Goiás", "Campo Limpo de Goiás", "Campos Belos","Campos Verdes", "Ceres", "Cezarina", "Chapadão do Céu", "Cidade Ocidental", "Cocalzinho de Goiás", "Colinas do Sul","Córrego do Ouro", "Corumbá de Goiás", "Cristalina", "Cristianópolis", "Cromínia", "Cumari", "Damianópolis","Damolândia", "Divinópolis de Goiás", "Doverlândia", "Edealina", "Edéia", "Estrela do Norte", "Faina","Fazenda Nova", "Firminópolis", "Flores de Goiás", "Formosa", "Formoso", "Goianápolis", "Goianésia", "Goianira","Goiás", "Goiatuba", "Goiás Velho", "Gurupi", "Iaciara", "Inhumas", "Ipameri", "Ipiranga de Goiás", "Itaberaí","Itaguari", "Itapaci", "Itapirapuã", "Itapuranga", "Itarumã", "Itauçu", "Itumbiara", "Ivolândia", "Jandaia","Jaraguá", "Jataí", "Jaupaci", "Jesúpolis", "Joviânia", "Jussara", "Lagoa Santa", "Leopoldo de Bulhões","Luziânia", "Mairipotaba", "Mambaí", "Mara Rosa", "Marzagão", "Mimoso de Goiás", "Mossâmedes", "Mozarlândia","Nerópolis", "Niquelândia", "Nova Crixás", "Nova Glória", "Nova Roma", "Novo Brasil", "Novo Gama", "Novo Planalto","Orizona", "Ouro Verde de Goiás", "Ouvidor", "Paranaiguara", "Paranoá", "Pedrinópolis", "Pirenópolis", "Planaltina","Pontalina", "Porangatu", "Portelândia", "Posse", "Professor Jamil", "Quirinópolis", "Rialma", "Rianápolis","Rio Verde", "Rubiataba", "Sanclerlândia", "Santa Bárbara de Goiás", "Santa Helena de Goiás", "Santa Isabel","Santa Rita do Araguaia", "Santa Rita do Novo Destino", "Santa Tereza de Goiás", "Santa Vitória", "Santo Antônio da Barra","Santo Antônio de Goiás", "Santo Antônio do Descoberto", "São Domingos", "São Francisco de Goiás", "São João d'Aliança","São João da Paraúna", "São Luís de Montes Belos", "São Miguel do Araguaia", "São Miguel do Passa Quatro","São Patrício", "São Simão", "Senador Canedo", "Silvânia", "Simolândia", "Sitio d’Abadia", "Teresina de Goiás","Trindade", "Trombas", "Turvânia", "Turvelândia", "Uirapuru", "Uruaçu", "Uruana", "Urutaí", "Valparaíso de Goiás", "Varjão", "Vianópolis", "Vila Boa", "Vila Propício"],

        "Maranhão": ["Açailândia", "Afonso Cunha", "Água Doce do Maranhão", "Alcântara", "Aldeias Altas", "Altamira do Maranhão","Alto Alegre do Maranhão", "Alto Alegre do Pindaré", "Alto Parnaíba", "Amarante do Maranhão", "Anajatuba","Anapurus", "Apicum-Açu", "Araguanã", "Araioses", "Arame", "Arari", "Axixá", "Bacabal", "Bacabeira","Bacuri", "Balsas", "Barão de Grajaú", "Barra do Corda", "Barreirinhas", "Bela Vista do Maranhão", "Belágua","Benedito Leite", "Bequimão", "Bernardo do Mearim", "Boa Vista do Gurupi", "Bom Jardim", "Bom Jesus das Selvas","Bom Lugar", "Brejo", "Brejo de Areia", "Buriti", "Buriti Bravo", "Buriticupu", "Buritirana", "Cachoeira Grande","Cajapió", "Cajari", "Campestre do Maranhão", "Cândido Mendes", "Cantanhede", "Capinzal do Norte", "Carolina","Carutapera", "Caxias", "Cedral", "Central do Maranhão", "Centro do Guilherme", "Centro Novo do Maranhão","Chapadinha", "Cidelândia", "Codó", "Coelho Neto", "Colinas", "Conceição do Lago-Açu", "Coroatá", "Cururupu","Davinópolis", "Dom Pedro", "Dórea", "Duque Bacelar", "Esperantinópolis", "Estreito", "Feira Nova do Maranhão","Fernando Falcão", "Formosa da Serra Negra", "Fortaleza dos Nogueiras", "Fortuna", "Grajau", "Guimarães","Humberto de Campos", "Icatu", "Igarapé do Meio", "Igarapé Grande", "Imperatriz", "Itaipava do Grajaú", "Itapecuru Mirim","Itapera", "Itinga do Maranhão", "Jatobá", "Jenipapo dos Vieiras", "João Lisboa", "Joselândia", "Junco do Maranhão","Lago da Pedra", "Lago do Junco", "Lago dos Rodrigues", "Lago Verde", "Lagoa do Mato", "Lagoa Grande do Maranhão","Lajeado Novo", "Lima Campos", "Loreto", "Luís Domingues", "Magalhães de Almeida", "Maracaçumé", "Marajá do Sena","Maranhão do Sul", "Mata Roma", "Matinha", "Matões", "Matões do Norte", "Milagres do Maranhão", "Mirador","Miranda do Norte", "Mirinzal", "Monção", "Montes Altos", "Morros", "Nina Rodrigues", "Nova Colinas", "Nova Iorque","Nova Olinda do Maranhão", "Nova Pedra", "Nova Pernambuco", "Nova Sabina", "Olho d'Água das Cunhãs", "Olho d'Água do Maranhão", "Palmeirândia", "Palmeirante", "Paraibano", "Parnarama", "Passagem Franca", "Pastos Bons", "Paulino Neves","Paulo Ramos", "Pedreiras", "Pedro do Rosário", "Peritoró", "Pindaré-Mirim", "Pinheiro", "Pio XII", "Pirapemas","Poção de Pedras", "Porto Franco", "Porto Rico do Maranhão", "Presidente Dutra", "Presidente Juscelino","Presidente Médici", "Presidente Sarney", "Raposa", "Riachão", "Ribamar Fiquene", "Rosário", "Sambaíba", "Santa Filomena",
        "Santa Helena", "Santa Inês", "Santa Luzia", "Santa Luzia do Paruá", "Santa Quitéria do Maranhão", "Santa Rita","Santa Rita do Tocantins", "Santo Amaro do Maranhão", "Santo Antônio dos Lopes", "São Benedito do Rio Preto","São Bento", "São Bernardo", "São Domingos do Maranhão", "São Francisco do Maranhão", "São João Batista","São João do Carú", "São João do Paraíso", "São João do Sul", "São João dos Patos", "São Luís", "São Luís Gonzaga do Maranhão","São Mateus do Maranhão", "São Miguel do Tapuio", "São Pedro dos Crentes", "São Raimundo das Mangabeiras","São Raimundo do Doca Bezerra", "São Roberto", "São Vicente Ferrer", "Satubinha", "Senador Alexandre Costa","Senador La Rocque", "Senador Sá", "Sítio Novo", "Tasso Fragoso", "Timbiras", "Timon", "Trizidela do Vale", "Tutóia","Urbano Santos", "Vargem Grande", "Viana", "Vila Nova dos Martírios", "Vitória do Mearim", "Vitorino Freire","Zé Doca"],

        "Mato Grosso": ["Água Boa", "Arenápolis", "Barra do Bugres", "Barra do Garças", "Campo Novo do Parecis", "Campo Verde", "Canarana","Carlinda", "Castanheira", "Chapada dos Guimarães", "Cláudia", "Cuiabá", "Denise", "Diamantino", "Dom Aquino","Feliz Natal", "Gaúcha do Norte", "General Carneiro", "Glória D'Oeste", "Guarantã do Norte", "Itiquira", "Jaciara","Jangada", "Jauru", "Juara", "Juína", "Juruena", "Lambari D'Oeste", "Lucas do Rio Verde", "Lucas do Rio Verde","Marcelândia", "Matupá", "Mirassol D'Oeste", "Nobres", "Nortelândia", "Nova Bandeirantes", "Nova Canãa do Norte","Nova Guarita", "Nova Marilândia", "Nova Maringá", "Nova Monte Verde", "Nova Mutum", "Nova Nazaré", "Nova Olímpia","Nova Ubiratã", "Novo Horizonte do Norte", "Novo Mundo", "Novo São Joaquim", "Novo Santo Antônio", "Paranaíta","Paranatinga", "Pedra Preta", "Peixoto de Azevedo", "Planalto da Serra", "Poxoréu", "Primavera do Leste", "Querência","Reserva do Cabaçal", "Ribeirão Cascalheira", "Ribeirãozinho", "Rio Branco", "Rio dos Peixes", "Rondolândia","Rondonópolis", "Rosário Oeste", "Salto do Céu", "Sapezal", "Serra Nova Dourada", "Sinop", "Sorriso", "Tabaporã","Tangará da Serra", "Tapurah", "Terra Nova do Norte", "Tesouro", "Torixoréu", "Várzea Grande", "Vila Rica","Vale de São Domingos", "Vila Bela da Santíssima Trindade", "Vila Galvão", "Vila Nova do Norte", "Vila Paulista","Vila Verde"],

        "Mato Grosso do Sul": ["Água Clara", "Alcinópolis", "Amambai", "Anastácio", "Anhembi", "Aparecida do Taboado","Aquidauana", "Aral Moreira","Bandeirantes", "Bataguassu", "Bataiporã", "Bela Vista", "Bodoquena", "Bonito", "Brasilândia", "Caarapó","Camapuã", "Campo Grande", "Caracol", "Cassilândia", "Chapadão do Sul", "Corguinho", "Corumbá", "Costa Rica","Douradina", "Dourados", "Eldorado", "Fátima do Sul", "Glória de Dourados", "Guia Lopes da Laguna", "Iguatemi","Inocência", "Itaporã", "Itaquiraí", "Ivinhema", "Japorã", "Jaraguari", "Jardim", "Juti", "Ladário","Laguna Carapã", "Maracaju", "Mara Rosa", "Miranda", "Mundo Novo", "Naviraí", "Nioaque", "Nova Alvorada do Sul","Nova Andradina", "Novo Horizonte do Sul", "Paranaíba", "Paranhos", "Pedro Gomes", "Ponta Porã", "Porto Murtinho","Ribas do Rio Pardo", "Rio Brilhante", "Rio Negro", "Rio Verde de Mato Grosso", "Rochedo", "Santa Rita do Pardo","São Gabriel do Oeste", "São João do Potengi", "São José do Rio Pardo", "São Pedro da União", "Sete Quedas","Sidrolândia", "Sonora", "Tacuru", "Taquarussu", "Terenos", "Três Lagoas", "Vicentina"],

        "Minas Gerais": [ "Abadia dos Dourados", "Abaeté", "Abre Campo", "Acaiaca", "Açucena", "Água Boa", "Água Comprida", "Aguanil","Águas Formosas", "Águas Vermelhas", "Aimorés", "Aiuruoca", "Alagoa", "Albertina", "Além Paraíba", "Alfenas","Alfredo Vasconcelos", "Almenara", "Alpercata", "Alpinópolis", "Alterosa", "Alto Caparaó", "Alto Rio Doce","Alvarenga", "Alvinópolis", "Amparo do Sul", "Andradas", "Andrelândia", "Angelândia", "Antônio Carlos","Antônio Dias", "Antônio Prado de Minas", "Aracitaba", "Araguari", "Arantina", "Araponga", "Araporã", "Arapuá","Araújos", "Araxá", "Arceburgo", "Areado", "Arealva", "Argirita", "Aricanduva", "Arinos", "Astolfo Dutra","Ataléia", "Augusto de Lima", "Baependi", "Baldim", "Bambuí", "Bandeira", "Bandeira do Sul", "Barão de Cocais","Barão de Monte Alto", "Barbacena", "Barra Longa", "Barroso", "Bela Vista de Minas", "Belmiro Braga","Belo Horizonte", "Belo Oriente", "Belo Vale", "Berilo", "Bertópolis", "Betim", "Bias Fortes", "Bicas","Biquinhas", "Boa Esperança", "Boa Família", "Bocaina de Minas", "Bocaiúva", "Bom Despacho", "Bom Jardim de Minas","Bom Jesus da Penha", "Bom Repouso", "Bom Sucesso", "Bonfim", "Bonfinópolis de Minas", "Borda da Mata","Brás Pires", "Brumadinho", "Brumado", "Bueno Brandão", "Buenópolis", "Bugre", "Buritis", "Buritizeiro","Cachoeira de Minas", "Cachoeira Dourada", "Caetanópolis", "Caeté", "Caio Martins", "Caldas", "Camacho","Camanducaia", "Cambuí", "Cambuquira", "Campanário", "Campanha", "Campestre", "Campina Verde", "Campo Belo","Campo do Meio", "Campo Florido", "Campos Gerais", "Canaã", "Canápolis", "Candeias", "Candeias do Jamari","Caparaó", "Capelinha", "Capinópolis", "Caputira", "Caraí", "Carandaí", "Carangola", "Caratinga", "Carbonita","Carmo da Cachoeira", "Carmo da Mata", "Carmo de Minas", "Carmo do Cajuru", "Carmo do Paranaíba", "Carmo do Rio Claro","Carmópolis de Minas", "Carneirinho", "Carvalhópolis", "Carvalho", "Cascalho Rico", "Cássia", "Cataguases","Catas Altas", "Catas Altas da Noruega", "Catolândia", "Catuji", "Celeste", "Chácara", "Chalé", "Chapada do Norte","Chapada Gaúcha", "Chaves", "Chiador", "Cipotânea", "Claraval", "Clarimundo", "Claro dos Poções", "Cláudio","Cocais", "Coluna", "Comissão de Frente", "Conceição de Ipanema", "Conceição do Pará", "Conceição do Rio Verde","Conceição dos Ouros", "Conselheiro Lafaiete", "Conselheiro Pena", "Conselheiro Rodrigues", "Contagem", "Corinto", 
        "Coroaci", "Coronel Fabriciano", "Coronel Murta", "Coronel Pacheco", "Coronel Xavier Chaves", "Coração de Jesus","Cordisburgo", "Cordislândia", "Cornélio Procópio", "Corrente", "Crisólito", "Cristais", "Cristina", "Crucilândia","Cruzeiro da Fortaleza", "Cruzeiro do Sul", "Curvelo", "Data", "Delfim Moreira", "Delfinópolis", "Delta", "Descoberto","Desemboque", "Desterro de Entre Rios", "Desterro do Melo", "Diamantina", "Diamantina do Norte", "Diogo de Vasconcelos","Divinésia", "Divino", "Divinópolis", "Divisa Alegre", "Divisa Nova", "Divisópolis", "Dom Bosco", "Dom Cavati","Dom Helvécio", "Dom Joaquim", "Dom Silvério", "Dom Viçoso", "Dona Euzébia", "Dores de Campos", "Dores do Indaiá","Dores do Turvo", "Doresópolis", "Douradoquara", "Doutor Campolina", "Doutor Edson", "Doutor Gama", "Doutor Jorge","Doutor Leôncio", "Doutor Pereira", "Doutor Siqueira", "Doutor Vargas", "Dourado", "Dourados", "Durandé", "Elói Mendes","Encruzilhada", "Espirito Santo do Dourado", "Espírito Santo do Rio Abaixo", "Espírito Santo do São Francisco","Espírito Santo do Tijuco", "Esmeraldas", "Estiva", "Estrela Dalva", "Estrela do Indaiá", "Estrela do Sul","Extrema", "Fama", "Faria Lemos", "Felisburgo", "Felipe dos Santos", "Ferros", "Fervedouro", "Florestal","Formiga", "Formoso", "Fortaleza de Minas", "Fortuna de Minas", "Francisco Badaró", "Francisco Sá", "Francisco Mendes","Francisco Morato", "Franco da Rocha", "Frederico Westphalen", "Frederico Ozanam", "Frederico Morato", "Freire","Frei Inocêncio", "Frei Lagonegro", "Frei Gaspar", "Frei Leopoldo", "Frei Orlando", "Frei Renato", "Frei Roque","Frei São Tiago", "Frei Simão", "Frei Severino", "Frei Vítor", "Galiléia", "Gameleiras", "Galvão", "Gama","Gandarela", "Gandarela do Rio", "Gandarela de Minas", "Gandarela do Norte", "Gandarela do Sul", "Gandarela do Vale","Gandarela do Oeste", "Gandarela do Centro"],

        "Pará": [ "Aberlado Santos", "Acará", "Afuá", "Água Azul do Norte", "Alenquer", "Algodoal", "Altamira", "Anajás","Ananindeua", "Anapu", "Augusto Corrêa", "Aurora do Pará", "Aveiro", "Bagre", "Baião", "Bannach", "Barcarena","Belém", "Belterra", "Benevides", "Berkel", "Bom Jesus do Tocantins", "Bonito", "Bragança", "Brejo Grande do Araguaia","Breves", "Bujaru", "Cachoeira do Arari", "Canaã dos Carajás", "Capitão Poço", "Castanhal", "Chaves", "Colares","Conceição do Araguaia", "Cumaru do Norte", "Curionópolis", "Dom Eliseu", "Eldorado dos Carajás", "Esperança","Floresta do Araguaia", "Garrafão do Norte", "Goianésia do Pará", "Gurupá", "Irituia", "Itaituba", "Itupiranga","Jacareacanga", "Jacundá", "Juruti", "Limoeiro do Ajuru", "Mãe do Rio", "Marabá", "Maracanã", "Marapanim", "Marituba","Medicilândia", "Melgaço", "Mãe do Rio", "Moju", "Monte Alegre", "Muaná", "Muaná", "Nova Ipixuna", "Nova Esperança","Novo Progresso", "Novo Repartimento", "Óbidos", "Oeiras do Pará", "Oriximiná", "Ourém", "Ourilândia do Norte","Paragominas", "Parauapebas", "Paulinia", "Peixe-Boi", "Prainha", "Redenção", "Rio Maria", "Rurópolis", "Salinópolis","Salvaterra", "Santa Bárbara do Pará", "Santa Cruz do Arari", "Santa Isabel do Pará", "Santa Luzia do Pará", "Santa Maria das Barreiras","Santa Maria do Pará", "Santa Rosa do Pará", "Santarém", "Santarém Novo", "Santo Antônio do Tauá", "São Caetano de Odivelas","São Domingos do Araguaia", "São Félix do Xingu", "São Francisco do Pará", "São João da Ponta", "São João de Pirabas","São Miguel do Guamá", "São Sebastião da Boa Vista", "São Valério do Sul", "Soure", "Tailândia", "Terra Alta", "Terra Santa","Tomé-Açu", "Tracuateua", "Trairão", "Turiaçu", "Ulianópolis", "Uruará", "Vigia", "Viseu", "Viseu do Pará","Xinguara"],

        "Paraíba": ["Água Branca", "Aguiar", "Alagoa Grande", "Alagoa Nova", "Alagoinha", "Alcantil", "Algodão de Jandaíra", "Amparo","Aparecida", "Areia", "Areia de Baraúnas", "Aroeiras", "Assunção", "Baía da Traição", "Bananeiras", "Baraúna","Barra de Santa Rosa", "Barra de São Miguel", "Bayeux", "Belém", "Belém de Brejo do Cruz", "Bernardino Batista","Boa Ventura", "Boa Esperança", "Boa Vista", "Bom Jesus", "Bom Sucesso", "Bonito de Santa Fé", "Boqueirão", "Borborema","Brejo do Cruz", "Brejo dos Santos", "Caaporã", "Cabedelo", "Cachoeira dos Índios", "Cacimba de Areia", "Cacimba de Dentro","Cacimbas", "Caiçara", "Cajazeiras", "Cajazeirinhas", "Caldas Brandão", "Camalaú", "Campina Grande", "Capim", "Carrapateira","Casserengue", "Caturité", "Conde", "Congo", "Coremas", "Cruz do Espírito Santo", "Cubati", "Cuité", "Cuité de Mamanguape","Curral de Cima", "Curral Velho", "Damião", "Diamante", "Dona Inês", "Duas Estradas", "Emas", "Esperança", "Fagundes","Frei Martinho", "Gado Bravo", "Guarabira", "Gurinhém", "Gurjão", "Ibiara", "Igaracy", "Imaculada", "Ingá", "Itabaiana","Itaporanga", "Itapororoca", "Itatuba", "Jacaraú", "Jacaúna", "Jericó", "João Pessoa", "Juarez Távora", "Juazeirinho","Junco do Sul", "Juripiranga", "Juru", "Lagoa", "Lagoa de Dentro", "Lagoa Seca", "Lastro", "Livramento", "Logradouro","Lucena", "Mãe d'Água", "Malta", "Mamanguape", "Mari", "Marizópolis", "Massaranduba", "Mataraca", "Matinhas", "Mato Grosso","Maturéia", "Monte Horebe", "Monteiro", "Mulungú", "Natuba", "Nazarezinho", "Nova Floresta", "Nova Olinda", "Nova Palmeira","Olho d'Água", "Olivedos", "Ouro Velho", "Parari", "Passagem", "Patos", "Paulista", "Pedra Lavrada", "Pedras de Fogo","Pedro Régis", "Piancó", "Picuí", "Pilar", "Pilões", "Pilõezinhos", "Pirpirituba", "Pitimbu", "Pocinhos", "Poço de José de Moura","Pombal", "Prata", "Princesa Isabel", "Puxinanã", "Queimadas", "Remígio", "Riachão", "Riachão do Bacamarte", "Riacho de Santo Antônio","Riacho dos Cavalos", "Rio Tinto", "Salgado de São Félix", "Salgado de São Sebastião", "Santa Cecília", "Santa Cruz", "Santa Helena","Santa Inês", "Santa Luzia", "Santa Rita", "Santa Teresinha", "Santarém", "São Bento", "São Bentinho", "São Domingos","São Francisco", "São João do Rio do Peixe", "São João do Tigre", "São José da Lagoa Tapada", "São José de Espinharas","São José dos Ramos", "São José dos Cordeiros", "São José dos Pinhais", "São João de Piranhas", "São Mamede", "São Miguel de Taipu",
        "São Sebastião de Lagoa de Roça", "São Sebastião do Umbuzeiro", "São Vicente do Seridó", "Sapé", "Serra Branca", "Serra da Raiz","Serra Grande", "Serra Redonda", "Sertãozinho", "Sobrado", "Solânea", "Soledade", "São João do Rio do Peixe", "São João do Tigre","São José de Espinharas", "São José dos Pinhais", "São José dos Cordeiros", "São José dos Ramos", "São Miguel de Taipu","São Sebastião de Lagoa de Roça", "São Sebastião do Umbuzeiro", "São Vicente do Seridó", "Sapé", "Serra Branca", "Serra da Raiz","Serra Grande", "Serra Redonda", "Sertãozinho", "Sobrado", "Solânea", "Soledade", "São José do Bonfim", "São João do Rio do Peixe","São João do Tigre", "São José de Espinharas", "São José dos Pinhais", "São José dos Cordeiros", "São José dos Ramos","São Miguel de Taipu", "São Sebastião de Lagoa de Roça", "São Sebastião do Umbuzeiro", "São Vicente do Seridó", "Sapé","Serra Branca", "Serra da Raiz", "Serra Grande", "Serra Redonda", "Sertãozinho", "Sobrado", "Solânea", "Soledade"],

        "Paraná": ["Abatiá", "Adrianópolis", "Agudos do Sul", "Almirante Tamandaré", "Altamira do Paraná", "Alto Paraíso", "Alto Paraná","Alvorada do Sul", "Amaporã", "Ampére", "Anahy", "Andirá", "Ângulo", "Antonina", "Antônio Olinto", "Apucarana","Arapongas", "Arapoti", "Arapuã", "Arealva", "Ariranha do Ivaí", "Assaí", "Astorga", "Atalaia", "Balsa Nova","Bandeirantes", "Barbosa Ferraz", "Barracão", "Barra do Jacaré", "Bela Vista do Paraíso", "Bituruna", "Boa Esperança","Boa Ventura de São Roque", "Boa Vista da Aparecida", "Bocaiúva do Sul", "Bom Jesus do Sul", "Bom Sucesso", "Borrazópolis","Braganey", "Brasilândia do Sul", "Cafeara", "Cafelândia", "Cairú", "Cambara", "Campina da Lagoa", "Campina do Sul","Campo Bonito", "Campo do Tenente", "Campo Largo", "Campo Magro", "Campo Mourão", "Candói", "Cantagalo", "Carambeí","Carlópolis", "Cascavel", "Castro", "Catanduvas", "Centenário do Sul", "Cerro Azul", "Chopinzinho", "Cianorte","Cidade Gaúcha", "Clevelândia", "Colombo", "Colorado", "Comboni", "Congonhinhas", "Conselheiro Mairinck", "Contenda","Corbelia", "Cornélio Procópio", "Coronel Domingos Soares", "Coronel Vivida", "Corumbataí do Sul", "Cruz Machado","Cruzeiro do Iguaçu", "Cruzeiro do Oeste", "Cruzeiro do Sul", "Curitiba", "Diamante do Norte", "Diamante do Sul","Dois Vizinhos", "Douradina", "Doutor Camargo", "Engenheiro Beltrão", "Esperança Nova", "Espigão Alto do Iguaçu","Faxinal", "Fazenda Rio Grande", "Flor da Serra do Sul", "Floraí", "Floresta", "Floresta do Araguaia", "Florence","Formosa do Oeste", "Foz do Iguaçu", "Francisco Beltrão", "General Carneiro", "Guaira", "Guarapuava", "Guarujá do Sul","Guarutuba", "Herval", "Ibiporã", "Icaraíma", "Iguaraçu", "Iguaçu", "Iguatu", "Imbituva", "Inácio Martins","Indianópolis", "Inhaúma", "Ipiranga", "Iracema do Oeste", "Irati", "Iretama", "Itaguajé", "Itaipulândia", "Itaipulândia","Ivaté", "Ivatuba", "Jaboti", "Jacarezinho", "Jaguapitã", "Jaguariaíva", "Jandaia do Sul", "Jardim Alegre", "Jardim Olinda","Jataizinho", "Jesuítas", "Joaquim Távora", "Joinville", "Joaquim Távora", "José de Freitas", "José Bonifácio","Juara", "Jussara", "Lapa", "Laranjeiras do Sul", "Laranjal", "Leópolis", "Lidianópolis", "Lindoeste", "Londrina","Luiziana", "Mallet", "Mallet", "Manfrinópolis", "Maringá", "Matelândia", "Mato Rico", "Matozinhos", "Mauá da Serra","Medianeira", "Melo", "Missal", "Miraselva", "Mirador", "Missal", "Morrinhos do Sul", "Mossoró", "Muriaé", "Nambuja",
        "Nova América da Colina", "Nova Cantu", "Nova Esperança do Sul", "Nova Fátima", "Nova Laranjeiras", "Nova Londrina","Nova Olímpia", "Nova Santa Bárbara", "Novo Itacolomi", "Novo São Joaquim", "Ouro Verde do Oeste", "Palmas", "Palmeira","Palmital", "Paraíso do Norte", "Paranacity", "Paraná", "Paranaguá", "Paranavaí", "Passo do Camargo", "Pato Branco","Paula Freitas", "Paulo Frontin", "Peabiru", "Perobal", "Pinhão", "Piraí do Sul", "Pitangueiras", "Planalto","Planalto", "Prado Ferreira", "Pranchita", "Prudentópolis", "Quatro Barras", "Querência do Norte", "Quinta do Sol","Quinta do Sul", "Ramilândia", "Rancho Alegre", "Realeza", "Reserva", "Reserva do Iguaçu", "Ribeirão Claro", "Ribeirão do Pinhal","Ribeirão do Sul", "Rio Azul", "Rio Bonito do Iguaçu", "Rio Branco do Ivaí", "Rio Branco do Sul", "Rio Negro","Rolândia", "Roncador", "Sabáudia", "Salgado Filho", "Salles de Oliveira", "Santa Amélia", "Santa Cecília", "Santa Cruz de Monte Castelo","Santa Fé", "Santa Helena", "Santa Isabel do Ivaí", "Santa Mariana", "Santa Tereza do Oeste", "Santana do Itararé","Santo Antônio da Platina", "Santo Antônio do Caiuá", "São Carlos do Ivaí", "São João", "São João do Ivaí", "São João do Triunfo","São Jorge do Ivaí", "São Jorge do Patrocínio", "São José da Boa Vista", "São José dos Pinhais", "São Mateus do Sul","São Miguel do Iguaçu", "São Pedro do Iguaçu", "São Tomé", "Sapopema", "Siqueira Campos", "Telêmaco Borba", "Terra Boa","Terra Rica", "Tibagi", "Tijucas do Sul", "Toledo", "Tomazina", "Três Barras do Paraná", "Três Fronteiras", "Tunas do Paraná","Turvo", "Ubiratã", "Umuarama", "União da Vitória", "Uniflor", "Ventania", "Verê", "Vila Velha", "Virmond", "Vitorino","Wenceslau Braz", "Xambrê"],


        "Pernambuco": ["Recife","Olinda","Jaboatão dos Guararapes","Caruaru","Petrolina","Garanhuns","Igarassu","Paulista","Cabo de Santo Agostinho","Vitória de Santo Antão"],

        "Piauí" : ["Teresina", "Parnaíba", "Picos", "Floriano", "Piripiri", "Campo Maior", "Altos", "Barras", "União", "Esperantina", "Oeiras", "José de Freitas","Pedro II", "Cocal", "Miguel Alves", "Batalha", "Luis Correia", "Amarante", "São Raimundo Nonato", "Cocal dos Alves"],

        "Rio de Janeiro": ["Angra dos Reis", "Araruama", "Areal", "Barra do Piraí", "Barra Mansa", "Belford Roxo", "Bom Jardim", "Bom Jesus do Itabapoana", "Cabo Frio", "Cachoeiras de Macacu", "Cambuci", "Campos dos Goytacazes", "Cantagalo", "Carapebus", "Cardoso Moreira", "Casimiro de Abreu", "Conceição de Macabu", "Cordeiro", "Duas Barras", "Duque de Caxias", "Engenheiro Paulo de Frontin", "Guapimirim", "Iguaba Grande", "Itaboraí", "Itaguaí", "Italva", "Itaocara", "Japeri", "Laje do Muriaé", "Macaé", "Macuco", "Magé", "Mangaratiba", "Maricá", "Mendes", "Mesquita", "Miguel Pereira", "Miracema", "Natividade", "Nilópolis", "Niterói", "Nova Friburgo", "Nova Iguaçu", "Paracambi", "Paraíba do Sul", "Paraty", "Paty do Alferes", "Petrópolis", "Pinheiral", "Piraí", "Porciúncula", "Quatis", "Queimados", "Resende", "Rio Bonito", "Rio Claro", "Rio de Janeiro", "Santa Maria Madalena", "Santo Antônio de Pádua", "São Fidélis", "São Francisco de Itabapoana", "São Gonçalo", "São João de Meriti", "São José de Ubá", "São Pedro da Aldeia", "São Sebastião do Alto", "Sapucaia", "Seropédica", "Silva Jardim", "Tanguá", "Teresópolis", "Três Rios", "Valença", "Varre-Sai", "Vassouras", "Volta Redonda"],

        "Rio Grande do Norte": ["Acari", "Açu", "Afonso Bezerra", "Água Nova", "Alexandria", "Almino Afonso", "Alto do Rodrigues", "Areia Branca", "Ares", "Assu", "Baía Formosa", "Baraúna", "Barcelona", "Bento Fernandes", "Boa Saúde", "Bodó", "Bom Jesus", "Brejinho", "Caiçara do Norte", "Caiçara do Sul", "Caicó", "Campo Redondo", "Canguaretama", "Caraúbas", "Carnaúba dos Dantas", "Carnaubais", "Ceará-Mirim", "Cerro Corá", "Coronel Ezequiel", "Coronel João Pessoa", "Currais Novos", "Doutor Severiano", "Extremoz", "Fernando Pedroza", "Florânia", "Francisco Dantas", "Francisco Morato", "Futebol Clube do Porto", "Galinhos", "Goianinha", "Governador Dix-Sept Rosado", "Grossos", "Ielmo Marinho", "Ipanguaçu", "Ipueira", "Itajá", "Itaú", "Jaçanã", "Jandaíra", "Janduís", "Januário Cicero", "Jardim de Angicos", "Jardim de Piranhas", "Jardim do Seridó", "João Câmara", "João Dias", "José da Penha", "Jundiá", "Lagoa de Velhos", "Lagoa Nova", "Lagoa Salgada", "Lajes", "Lajes Pintadas", "Luis Gomes", "Macau", "Major Sales", "Marcelino Vieira", "Martins", "Maxaranguape", "Messias Targino", "Montanhas", "Monte Alegre", "Monte das Gameleiras", "Mossoró", "Natal", "Nísia Floresta", "Nova Cruz", "Olho-d'Água do Borges", "Ouro Branco", "Paraná", "Parnamirim", "Passa e Fica", "Passagem", "Patu", "Pau dos Ferros", "Pedra Preta", "Pedro Avelino", "Pedro Velho", "Pendências", "Pilões", "Poço Branco", "Portalegre", "Porto do Mangue", "Rafael Fernandes", "Rafael Godeiro", "Riacho da Cruz", "Riacho de Santana", "Rio do Fogo", "Rodolfo Fernandes", "São Bento do Norte", "São Bento do Trairi", "São Fernando", "São Francisco do Oeste", "São Gonçalo do Amarante", "São João do Sabugi", "São José de Mipibu", "São José do Campestre", "São José do Seridó", "São Miguel", "São Miguel do Gostoso", "São Paulo do Potengi", "São Pedro", "São Rafael", "São Tomé", "São Vicente", "Senador Elói de Souza", "Senador Georgino Avelino", "Sítio Novo", "Taboleiro Grande", "Taipu", "Tangará", "Tenente Ananias", "Tenente Laurentino Cruz", "Tibau", "Tibau do Sul", "Timbaúba dos Batistas", "Tomba", "Três Marias", "Upanema", "Várzea", "Venha-Ver", "Vera Cruz", "Viçosa"],

        "Rio Grande do Sul": ["Aceguá", "Água Santa", "Ajuricaba", "Alecrim", "Alegrete", "Alegria", "Alvorada", "Ametista do Sul", "André da Rocha", "Anta Gorda", "Antônio Prado", "Aramburu", "Araricá", "Arroio do Meio", "Arroio do Sal", "Arroio dos Ratos", "Arvorezinha", "Augusto Pestana", "Bagé", "Balneário Pinhal", "Barão", "Barão de Cotegipe", "Barra do Ribeiro", "Barra do Quaraí", "Barra do Ribeiro", "Barra do Sul", "Barros Cassal", "Benjamin Constant do Sul", "Bento Gonçalves", "Bertópolis", "Boa Vista das Missões", "Boa Vista do Sul", "Bom Jesus", "Bom Princípio", "Bom Retiro do Sul", "Boqueirão do Leão", "Bossoroca", "Braga", "Brochier", "Butiá", "Cacique Doble", "Cacequi", "Camaquã", "Camargo", "Cambará do Sul", "Campestre da Serra", "Campina das Missões", "Campo Bom", "Campo Novo", "Campo Novo", "Campos Borges", "Candelária", "Candiota", "Canela", "Canguçu", "Canoas", "Capão Bonito do Sul", "Capão da Canoa", "Capão do Cipó", "Capão do Leão", "Capela de Santana", "Capitão", "Carazinho", "Carlos Barbosa", "Carlos Gomes", "Casca", "Caxias do Sul", "Centenário", "Cerrito", "Chapada", "Charqueadas", "Charrua", "Chiapetta", "Chorão", "Ciríaco", "Cruz Alta", "Cruzaltense", "Cruzaltense", "Cruzeiro do Sul", "David Canabarro", "Derrubadas", "Dilermando de Aguiar", "Dois Irmãos", "Dois Irmãos das Missões", "Dois Lajeados", "Dona Francisca", "Doutor Maurício Cardoso", "Eldorado do Sul", "Encantado", "Encruzilhada do Sul", "Engenho Velho", "Esmeralda", "Esperança do Sul", "Espumoso", "Estância Velha", "Estância Velha", "Esteio", "Estrela", "Estrela Velha", "Eusébio de Castro", "Farroupilha", "Faxinal do Soturno", "Faxinalzinho", "Feliz", "Flores da Cunha", "Floriano Peixoto", "Floriano Peixoto", "Fontoura Xavier", "Formigueiro", "Forquetinha", "Frederico Westphalen", "Garibaldi", "Garruchos", "Gaurama", "General Câmara", "Gentil", "Getúlio Vargas", "Giruá", "Glorinha", "Gramado", "Gravataí", "Guaporé", "Harmonia", "Herval", "Herval d'Oeste", "Ibiraiaras", "Ibirapuitã", "Ibirubá", "Igrejinha", "Ijuí", "Ilópolis", "Imbé", "Independência", "Inhacorá", "Ipê", "Ipiranga do Sul", "Itaara", "Itaqui", "Itaqui", "Itaqui", "Ivoti", "Jaboticaba", "Jacutinga", "Jaguarão", "Jaguaricatu", "Jari", "Júlio de Castilhos", "Juventude", "Lajeado"],

        "Rondônia": ["Alta Floresta d'Oeste", "Alto Alegre dos Parecis", "Alto Paraíso", "Alvorada d'Oeste", "Ariquemes", "Buritis", "Cabixi", "Cacoal", "Candeias do Jamari", "Castanheiras", "Cerejeiras", "Chupinguaia", "Colorado do Oeste", "Corumbiara", "Costa Marques", "Espigão d'Oeste", "Governador Jorge Teixeira", "Guajará-Mirim", "Itapuã do Oeste", "Jaru", "Ji-Paraná", "Machadinho d'Oeste", "Ministro Andreazza", "Mirante da Serra", "Monte Negro", "Nova Brasilândia d'Oeste", "Nova Mamoré", "Nova União", "Ouro Preto do Oeste", "Parecis", "Pimenta Bueno", "Porto Velho", "Presidente Médici", "Rio Crespo", "Rolim de Moura", "Santa Luzia d'Oeste", "São Francisco do Guaporé", "São Miguel do Guaporé", "Seringueiras", "Teixeirópolis", "Theobroma", "Vale do Anari", "Vale do Paraíso", "Vilhena"],

        "Roraima": ["Alto Alegre", "Amajari", "Boa Vista", "Bonfim", "Cantá", "Caracaraí", "Caroebe", "Iracema", "Mucajaí", "Normandia", "Pacaraima", "Rorainópolis", "São João da Baliza", "São Luiz", "Uiramutã"],

        "Santa Catarina" : ["Abdon Batista", "Abelardo Luz", "Agrolândia", "Agronômica", "Água Doce", "Águas Frias", "Águas Mornas", "Águas de Chapecó", "Alfredo Wagner", "Alto Bela Vista", "Anchieta", "Angelina", "Anita Garibaldi", "Anitápolis", "Antônio Carlos", "Apiúna", "Arabutã", "Araquari", "Araranguá", "Armazém", "Arroio Trinta", "Arvoredo", "Ascurra", "Atalanta", "Aurora", "Balneário Arroio do Silva", "Balneário Barra do Sul", "Balneário Camboriú", "Balneário Gaivota", "Bandeirante", "Barra Bonita", "Barra Velha", "Bela Vista do Toldo", "Belmonte", "Benedito Novo", "Biguaçu", "Blumenau", "Bocaina do Sul", "Bom Jardim da Serra", "Bom Jesus", "Bom Jesus do Oeste", "Bom Retiro", "Bombinhas", "Botuverá", "Braço do Norte", "Braço do Trombudo", "Brunópolis", "Brusque", "Caçador", "Caibi", "Calmon", "Camboriú", "Campo Alegre", "Campo Belo do Sul", "Campo Erê", "Campos Novos", "Canelinha", "Canoinhas", "Capão Alto", "Capinzal", "Capivari de Baixo", "Catanduvas", "Caxambu do Sul", "Celso Ramos", "Cerro Negro", "Chapadão do Lageado", "Chapecó", "Cocal do Sul", "Concórdia", "Cordilheira Alta", "Coronel Freitas", "Coronel Martins", "Correia Pinto", "Corupá", "Criciúma", "Cunha Porã", "Cunhataí", "Curitibanos", "Descanso", "Dionísio Cerqueira", "Dona Emma", "Doutor Pedrinho", "Entre Rios", "Ermo", "Erval Velho", "Faxinal dos Guedes", "Flor do Sertão", "Florianópolis", "Formosa do Sul"],

        "São Paulo": ["Adamantina", "Adolfo", "Aguaí", "Águas da Prata", "Águas de Lindóia", "Águas de Santa Bárbara", "Águas de São Pedro", "Agudos", "Alambari", "Alfredo Marcondes", "Altair", "Altinópolis", "Alto Alegre", "Alumínio", "Álvares Florence", "Álvares Machado", "Álvaro de Carvalho", "Alvinlândia", "Americana", "Américo Brasiliense", "Américo de Campos", "Amparo", "Analândia", "Andradina", "Angatuba", "Anhembi", "Anhumas", "Aparecida", "Aparecida d'Oeste", "Apiaí", "Araçariguama", "Araçatuba", "Araçoiaba da Serra", "Aramina", "Arandu", "Arapeí", "Araraquara", "Araras", "Arco-Íris", "Arealva", "Areias", "Areiópolis", "Ariranha", "Artur Nogueira", "Arujá", "Aspásia", "Assis", "Atibaia", "Auriflama", "Avaí", "Avanhandava", "Avaré", "Bady Bassitt", "Balbinos", "Bálsamo", "Bananal", "Barão de Antonina", "Barbosa", "Bariri", "Barra Bonita", "Barra do Chapéu", "Barra do Turvo", "Barretos", "Barrinha", "Barueri", "Bastos", "Batatais", "Bauru", "Bebedouro", "Bento de Abreu", "Bernardino de Campos", "Bertioga", "Bilac", "Birigui", "Biritiba-Mirim", "Boa Esperança do Sul", "Bocaina", "Bofete", "Boituva", "Bom Jesus dos Perdões", "Bom Sucesso de Itararé", "Borá", "Boracéia", "Borborema", "Borebi", "Botucatu", "Bragança Paulista", "Braúna", "Brejo Alegre", "Brodowski", "Brotas", "Buri", "Buritama", "Buritizal", "Cabrália Paulista", "Cabreúva", "Caçapava", "Cachoeira Paulista", "Caconde", "Cafelândia", "Caiabu", "Caieiras", "Caiuá", "Cajamar", "Cajati", "Cajobi", "Cajuru", "Campina do Monte Alegre", "Campinas", "Campo Limpo Paulista", "Campos Novos Paulista", "Campos do Jordão", "Cananéia", "Canas", "Cândido Mota", "Cândido Rodrigues", "Canitar","Pacaembu", "Palestina", "Palmares Paulista","Palmeira d'Oeste", "Palmital", "Panorama", "Paraguaçu Paulista", "Paraibuna", "Paraíso", "Paranapanema", "Paranapuã", "Parapuã", "Pardinho", "Pariquera-Açu", "Parisi", "Patrocínio Paulista", "Paulicéia", "Paulínia","Paulistânia", "Paulo de Faria", "Pederneiras", "Pedra Bela", "Pedranópolis", "Pedregulho", "Pedreira", "Pedrinhas Paulista", "Pedro de Toledo", "Penápolis", "Pereira Barreto", "Pereiras", "Peruíbe", "Piacatu", "Piedade", "Pilar do Sul", "Pindamonhangaba", "Pindorama", "Pinhalzinho", "Piquerobi", "Piquete", "Piracaia", "Piracicaba", "Piraju", "Pirajuí", "Pirangi", "Pirapora do Bom Jesus", "Pirapozinho", "Pirassununga", "Piratininga", "Pitangueiras"],

        "Sergipe": ["Amparo de São Francisco", "Aquidabã", "Aracaju", "Arauá", "Areia Branca", "Barra dos Coqueiros", "Boquim", "Brejo Grande", "Campo do Brito", "Canhoba", "Canindé de São Francisco", "Capela", "Carira", "Carmópolis", "Cedro de São João", "Cristinápolis", "Cumbe", "Divina Pastora", "Estância", "Feira Nova", "Frei Paulo", "Gararu", "General Maynard", "Graccho Cardoso", "Igreja Nova", "Indiaroba", "Itabaiana", "Itabaianinha", "Itabi", "Itaporanga d'Ajuda", "Japaratuba", "Japoatã", "Lagarto", "Laranjeiras", "Macambira", "Malhador", "Maruim", "Moita Bonita", "Monte Alegre de Sergipe", "Muribeca", "Neópolis", "Nossa Senhora da Glória", "Nossa Senhora das Dores", "Nossa Senhora de Lourdes", "Nossa Senhora do Socorro", "Pacatuba", "Pedra Mole", "Pedrinhas", "Pinhão", "Pirambu", "Poço Redondo", "Poço Verde", "Porto da Folha", "Propriá", "Riachuelo", "Ribeirópolis", "Rosário do Catete", "Salgado", "Santa Luzia do Itanhy", "Santa Rosa de Lima", "Santa Maria", "São Cristóvão", "São Domingos", "São Francisco", "São Miguel do Aleixo", "São Sebastião", "São Silveira", "São Braz", "São João de Carapina", "São João do Sobrado", "São João do Itanhy", "São João de Pirabas", "São João de Meriti", "São João Nepomuceno", "São Sebastião do Umbuzeiro", "Sergipe", "Simão Dias", "Siriri", "Telha", "Tobias Barreto", "Tomar do Geru", "Umbaúba"],

        "Tocantins":["Abreulândia", "Aguiarnópolis", "Aliança do Tocantins", "Almas", "Alvorada", "Ananás", "Angico", "Aparecida do Rio Negro", "Araguaína", "Araguanã", "Araguatins", "Arapoema", "Arraias", "Augustinópolis", "Aventureiro", "Barrolândia", "Belford Roxo", "Bom Jesus do Tocantins", "Brasilândia do Tocantins", "Brejinho de Nazaré", "Buriti do Tocantins", "Cachoeirinha", "Campos Lindos", "Cariri do Tocantins", "Carmolândia", "Carrasco Bonito", "Caseara", "Cidelândia", "Colinas do Tocantins", "Colméia", "Conceição do Tocantins", "Couto de Magalhães", "Cristalândia", "Crixás do Tocantins", "Dianópolis", "Divinópolis do Tocantins", "Dois Irmãos do Tocantins", "Dueré", "Esperantina", "Figueirópolis", "Filadélfia", "Formoso do Tocantins", "Fortaleza do Tabocão", "Goianorte", "Goiatins", "Guaraí", "Gurupi", "Ipueiras", "Itacajá", "Itaguatins", "Itapiratins", "Itaporã do Tocantins", "Jaú do Tocantins", "Juarina", "Lagoa da Confusão", "Lagoa do Tocantins", "Lajeado", "Lavandeira", "Lizarda", "Mateiros", "Maurilândia do Tocantins", "Miracema do Tocantins", "Miranorte", "Miranorte", "Monte do Carmo", "Monte Santo do Tocantins", "Muricilândia", "Nova Olinda", "Nova Rosalândia", "Palmeirante", "Palmeiras do Tocantins", "Palmeirópolis", "Paraíso do Tocantins", "Paraiso do Tocantins", "Pau D'arco", "Peixe", "Pindorama do Tocantins", "Piraquê", "Planaltina do Tocantins", "Ponte Alta do Tocantins", "Porto Nacional", "Recursolândia", "Riachinho", "Rianápolis", "Santa Fé do Araguaia", "Santa Maria do Tocantins", "Santa Rita do Tocantins", "Santa Tereza do Tocantins", "São Bento do Tocantins", "São Félix do Tocantins", "São Miguel do Tocantins", "São Salvador do Tocantins", "São Sebastião do Tocantins", "São Valério da Natividade", "Silvanópolis", "Sítio Novo do Tocantins", "Sucupira", "Tocantinópolis", "Tupirama", "Tupiratins", "Wanderlândia", "Wanderlândia"],


    },
    VE: {
        "Amazonas": ["Puerto Ayacucho", "Atabapo", "Atures", "Manapiare", "Yapacana", "La Esmeralda", "San Fernando de Atabapo", "San Carlos de Río Negro", "Maroa", "Santos de Atapapo", "Río Negro", "El Nula", "Maroa", "Santa Teresa del Tuy", "Puerto Páez"],

        "Anzoátegui":["Barcelona", "Puerto La Cruz", "Lechería", "El Tigre", "San Tomé", "Anaco", "El Palotal", "Cantaura", "El Chaparro", "San José de Guanipa", "Clarines", "Píritu", "El Peaje", "Santa Ana", "Soledad", "Naricual", "Guanipa", "El Tigrito", "Cantaura", "Santa Fe", "Cerro Azul", "Guanipa", "San Mateo"],

        "Apure": ["San Fernando de Apure", "Achaguas", "Biruaca", "Guasdualito", "Elorza", "Mantecal", "Bruzual", "Río Negro", "Pedro Camejo", "Juan Pablo Peñalosa", "San Juan de Payara", "Santa Rosalía", "La Victoria", "El Nula", "San Vicente"],

        "Aragua":["Maracay", "Turmero", "La Victoria", "Valencia", "Cagua", "San Sebastián", "Tucupido", "Zaraza", "El Limón", "Villa de Cura", "Las Tejerías", "San Juan de los Morros", "Campo Elías Delgado", "San Antonio de Los Altos", "Santa Cruz"],

        "Barinas": ["Barinas", "Ciudad Bolívar", "Ciudad de Nutrias", "Sabaneta", "Socopó", "La Carrereña", "Río Negro", "El Cantón", "Canoabo", "San Silvestre", "Alto Barinas", "Los Taques", "Punto Fijo", "San Fernando"],

        "Bolivar": ["Ciudad Bolívar", "Puerto Ordaz", "San Félix", "Upata", "El Callao", "Ciudad Guayana", "Tumeremo", "Gran Sabana", "Caicara del Orinoco", "Santa Elena de Uairén", "Bolívar", "Canaima", "El Dorado", "Piar", "Guasipati"],

        "Carabobo": ["Valencia", "Naguanagua", "Puerto Cabello", "Mariara", "Tocuyito", "San Diego", "Los Guayos", "Guacara", "Carlos Arvelo", "Bejuma", "Montalbán", "Juan José Mora", "Libertador", "San Joaquín", "Morón"],

        "Cojedes": ["San Carlos", "Tinaquillo", "Las Vegas", "El Baño",  "Aroa", "Zamora", "La Aguadita", "La Caramuca", "Cojedes", "El Toco"],

        "Delta Amacuro": ["Tucupita", "Pedernales", "Casacoima", "Curiapo", "San José de Bucaral",  "Barrancas del Orinoco", "Casanay", "Maturín", "San Juan de Capistrano"],

        "Distrito Federal":["Caracas", "El Hatillo", "Chacao", "Sucre", "Baruta", "Libertador", "San Juan", "Altagracia", "La Vega", "San Pedro", "Santa Teresa"],

        "Falcón":["Coro", "Carirubana", "Dabajuro", "La Vela de Coro", "Punto Fijo", "Colina", "Mirimire", "San Francisco", "Cumarebo", "Adícora", "Moruy", "Jadacaquiva", "Piedra de Moler", "Los Taques", "Dabajuro"],

        "Guárico": ["San Juan de los Morros", "Valle de la Pascua", "Calabozo", "El Sombrero", "San Fernando de Apure", "Cazorla", "San Sebastián de los Reyes", "Guasimal", "Zaraza", "Cúpira", "Píritu", "Las Mercedes", "San José de Guaribe", "Parapara", "Santa María"],

        "Lara": ["Barquisimeto", "Cabudare", "Guanare", "Carora", "El Tocuyo", "Quíbor", "Yaritagua", "Sanare", "Morán", "La Caramuca", "Castañeda", "La Palmera", "Siquisique", "Torres", "Cerro Altagracia"],

        "Mérida": ["El Vigía", "Tovar", "Rivas Dávila", "Santa Bárbara", "Zeus", "La Azulita", "Jají", "Chachopo", "Mucuchíes", "Mucurubá", "San Rafael de Mucuchíes", "La Parroquia", "La Azulita", "Santo Domingo"],

        "Miranda": ["Los Teques", "Guatire", "Guarenas", "Carrizal", "Baruta", "El Hatillo", "Chacao", "San Antonio de los Altos", "San Fernando de Apure", "Santa Teresa del Tuy", "Cúa", "Ocumare del Tuy", "Charallave", "El Paraíso", "Tacarigua"],

        "Monagas": ["Maturín", "Cumaná", "Punta de Mata", "Caripito", "Aguasay", "Jusepín", "Santa Bárbara", "Las Mercedes", "Temblador", "Canaima", "La Toscana", "El Tejero", "Quiriquire"],

        "Nueva Esparta": ["La Asunción", "Porlamar", "Margarita", "Juangriego", "El Valle del Espíritu Santo", "San Pedro", "Antolín del Campo", "Bachaquero", "La Guardia", "Pampatar", "Coche", "Punta de Piedras"],

        "Portuguesa":["Acarigua", "Aroa", "Araure", "Guanare", "Guanarito", "Ospino", "Páez", "San Rafael de Onoto", "Biscucuy", "Papelón", "Coro", "Maroa", "Guanare"],

        "Sucre":["Cumaná", "Carúpano", "Yaguaraparo", "Guiria", "Cumanacoa", "Río Caribe", "Onoto", "Araya", "El Pilar", "Santa Fe", "Maturín", "San Félix", "El Valle", "Los Guayos"],

        "Táchira":["San Cristóbal", "La Grita", "Colón", "Táriba", "Rubio", "El Cobre", "Capacho", "Ureña", "Pregonero", "Cordero", "San Antonio del Táchira", "Andrés Bello", "San José de Bolívar", "Palmira"],

        "Trujillo":["Trujillo", "Valera", "Boconó", "El Dividive", "Campo Elías Delgado", "Escuque", "La Quebrada", "Trujillo", "San Lázaro", "Betijoque", "Carvajal", "La Ceiba", "Valera", "Monte Carmelo", "La Rasa"],

        "Vargas":["La Guaira", "Caraballeda", "Carayaca", "Maiquetía", "Naiguatá", "El Junko", "Cata", "Los Caracas", "Coro", "Canoabo", "San José de La Costa", "Catia La Mar", "Canoabo"],

        "Yaracuy":["San Felipe", "Yaritagua", "Chivacoa", "Cocorote", "Nirgua", "La Unión", "San Pablo", "Arístides Bastidas", "Morón", "Sabana de Mendoza", "El Tocuyo", "Bruzual", "Guama"],

        "Zulia":["Maracaibo", "San Francisco", "Ciudad Ojeda", "Cabimas", "La Villa del Rosario", "Valmore Rodríguez", "Santa Rita", "La Concepción", "Germán Ríos Linares", "Jesús Enrique Lossada", "Miranda", "La Cañada de Urdaneta", "Tía Juana"],
    }
};